syntax = "proto3";

package vericov.git.v1;

option java_multiple_files = true;
option java_package = "dev.vericov.git.grpc.v1";

service GitActionService {
  rpc GetPullRequestDiff (GetPullRequestDiffRequest) returns (PullRequestDiff);
}

message GetPullRequestDiffRequest {
  string repository_id = 1;
  int32 pull_request_number = 2;
}

message PullRequestDiff {
  string repository_id = 1;
  int32 pull_request_number = 2;
  string base_sha = 3;
  string head_sha = 4;
  repeated DiffFile files = 5;
}

message DiffFile {
  string path = 1;
  string status = 2;
}
